#:schema node_modules/wrangler/config-schema.json
name = "twikoo-cloudflare"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"                                       # available in your Worker on env.DB
database_name = "twikoo"
database_id = "0b93244d-79a4-4139-884a-122c1ab3e2ba"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://twikoo.r2.maotaos.com"

[dev]
port = 5000
